# typed: false
# frozen_string_literal: true

# Template for avivsinai/homebrew-tap Formula/sabx.rb (v0.1.11).
# GoReleaser `brews` regenerates this file on each tagged release.
# This file was generated by GoReleaser. DO NOT EDIT.
class Sabx < Formula
  desc "Full-fidelity SABnzbd CLI"
  homepage "https://github.com/avivsinai/sabx"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/avivsinai/sabx/releases/download/v0.1.11/sabx_0.1.11_darwin_x86_64.tar.gz"
      sha256 "969af50573877acba3973b0791232c30238c18791f765c3bffee6249a33f0e22"

      define_method(:install) do
        bin.install "sabx"
        if OS.mac?
          system "/usr/bin/codesign", "--force", "--sign", "-", "--identifier", "io.github.avivsinai.sabx", bin/"sabx"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/avivsinai/sabx/releases/download/v0.1.11/sabx_0.1.11_darwin_arm64.tar.gz"
      sha256 "2a258f056940a8837fee2d8acc81b6bd4f9de92a4e543807ae8f5e6209b2e466"

      define_method(:install) do
        bin.install "sabx"
        if OS.mac?
          system "/usr/bin/codesign", "--force", "--sign", "-", "--identifier", "io.github.avivsinai.sabx", bin/"sabx"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/sabx/releases/download/v0.1.11/sabx_0.1.11_linux_x86_64.tar.gz"
      sha256 "6d4c052d31dba5393934c0b61c4effd6aa51065e042b9211e9868e437c9ee4fc"
      define_method(:install) do
        bin.install "sabx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/avivsinai/sabx/releases/download/v0.1.11/sabx_0.1.11_linux_arm64.tar.gz"
      sha256 "e1633b14942b699f2616dd46c0addfa8772914bad6c7e9bffea87320ae943c19"
      define_method(:install) do
        bin.install "sabx"
      end
    end
  end

  test do
    system "#{bin}/sabx", "--version"
  end
end
