name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I find it difficult to... / I wish I could...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: Add a new command `sabx queue compact` that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I could use... but it doesn't...

  - type: textarea
    id: api-coverage
    attributes:
      label: SABnzbd API Coverage
      description: If this relates to SABnzbd API functionality, which mode(s) or endpoint(s)?
      placeholder: |
        SABnzbd API mode: `get_config`
        Documentation: https://sabnzbd.org/wiki/...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you'd use this feature
      placeholder: |
        ```bash
        sabx queue compact --threshold 10
        ```
      render: bash

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
